

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1452, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoadData_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LoadData_GroupBox.setGeometry(QtCore.QRect(50, 60, 251, 441))
        self.LoadData_GroupBox.setObjectName("LoadData_GroupBox")
        self.LoadFolder_Button = QtWidgets.QPushButton(self.LoadData_GroupBox)
        self.LoadFolder_Button.setGeometry(QtCore.QRect(50, 50, 151, 41))
        self.LoadFolder_Button.setObjectName("LoadFolder_Button")
        self.LoadImageL_Button = QtWidgets.QPushButton(self.LoadData_GroupBox)
        self.LoadImageL_Button.setGeometry(QtCore.QRect(50, 190, 151, 41))
        self.LoadImageL_Button.setObjectName("LoadImageL_Button")
        self.LoadImageR_Button = QtWidgets.QPushButton(self.LoadData_GroupBox)
        self.LoadImageR_Button.setGeometry(QtCore.QRect(50, 330, 151, 41))
        self.LoadImageR_Button.setObjectName("LoadImageR_Button")
        self.LoadFolder_Label = QtWidgets.QLabel(self.LoadData_GroupBox)
        self.LoadFolder_Label.setGeometry(QtCore.QRect(50, 100, 151, 21))
        self.LoadFolder_Label.setText("No folder loaded")
        self.LoadFolder_Label.setObjectName("LoadFolder_Label")
        self.LoadImageL_Label = QtWidgets.QLabel(self.LoadData_GroupBox)
        self.LoadImageL_Label.setGeometry(QtCore.QRect(50, 240, 151, 21))
        self.LoadImageL_Label.setText("No image loaded")
        self.LoadImageL_Label.setObjectName("LoadImageL_Label")
        self.LoadImageR_Label = QtWidgets.QLabel(self.LoadData_GroupBox)
        self.LoadImageR_Label.setGeometry(QtCore.QRect(50, 380, 151, 21))
        self.LoadImageR_Label.setText("No image loaded")
        self.LoadImageR_Label.setObjectName("LoadImageR_Label")
        self.FindContour_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.FindContour_GroupBox.setGeometry(QtCore.QRect(320, 60, 251, 441))
        self.FindContour_GroupBox.setObjectName("FindContour_GroupBox")
        self.DrawContour_Button = QtWidgets.QPushButton(self.FindContour_GroupBox)
        self.DrawContour_Button.setGeometry(QtCore.QRect(50, 50, 151, 41))
        self.DrawContour_Button.setObjectName("DrawContour_Button")
        self.CountRings_Button = QtWidgets.QPushButton(self.FindContour_GroupBox)
        self.CountRings_Button.setGeometry(QtCore.QRect(50, 190, 151, 41))
        self.CountRings_Button.setObjectName("CountRings_Button")
        self.RingImg1_Label = QtWidgets.QLabel(self.FindContour_GroupBox)
        self.RingImg1_Label.setGeometry(QtCore.QRect(50, 240, 151, 21))
        self.RingImg1_Label.setText("")
        self.RingImg1_Label.setObjectName("RingImg1_Label")
        self.RingImg2_Label = QtWidgets.QLabel(self.FindContour_GroupBox)
        self.RingImg2_Label.setGeometry(QtCore.QRect(50, 270, 151, 21))
        self.RingImg2_Label.setText("")
        self.RingImg2_Label.setObjectName("RingImg2_Label")
        self.Calibration_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Calibration_GroupBox.setGeometry(QtCore.QRect(590, 60, 251, 441))
        self.Calibration_GroupBox.setObjectName("Calibration_GroupBox")
        self.FindCorners_Button = QtWidgets.QPushButton(self.Calibration_GroupBox)
        self.FindCorners_Button.setGeometry(QtCore.QRect(50, 50, 151, 41))
        self.FindCorners_Button.setObjectName("FindCorners_Button")
        self.FindIntrinsic_Button = QtWidgets.QPushButton(self.Calibration_GroupBox)
        self.FindIntrinsic_Button.setGeometry(QtCore.QRect(50, 110, 151, 41))
        self.FindIntrinsic_Button.setObjectName("FindIntrinsic_Button")
        self.ChessBoard_ComboBox = QtWidgets.QComboBox(self.Calibration_GroupBox)
        self.ChessBoard_ComboBox.setGeometry(QtCore.QRect(80, 170, 91, 22))
        self.ChessBoard_ComboBox.setObjectName("ChessBoard_ComboBox")
        self.ChessBoard_ComboBox.addItems([str(i) for i in range(1,16)]) #自己設定的
        self.FindExtrinsic_Button = QtWidgets.QPushButton(self.Calibration_GroupBox)
        self.FindExtrinsic_Button.setGeometry(QtCore.QRect(50, 210, 151, 41))
        self.FindExtrinsic_Button.setObjectName("FindExtrinsic_Button")
        self.FindDistortion_Button = QtWidgets.QPushButton(self.Calibration_GroupBox)
        self.FindDistortion_Button.setGeometry(QtCore.QRect(50, 270, 151, 41))
        self.FindDistortion_Button.setObjectName("FindDistortion_Button")
        self.ShowResult_Button = QtWidgets.QPushButton(self.Calibration_GroupBox)
        self.ShowResult_Button.setGeometry(QtCore.QRect(50, 330, 151, 41))
        self.ShowResult_Button.setObjectName("ShowResult_Button")
        self.AugmentedReality_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.AugmentedReality_GroupBox.setGeometry(QtCore.QRect(870, 60, 251, 441))
        self.AugmentedReality_GroupBox.setObjectName("AugmentedReality_GroupBox")
        self.ShowWordOnBoard_Button = QtWidgets.QPushButton(self.AugmentedReality_GroupBox)
        self.ShowWordOnBoard_Button.setGeometry(QtCore.QRect(40, 210, 171, 41))
        self.ShowWordOnBoard_Button.setObjectName("ShowWordOnBoard_Button")
        self.ShowWordVertically_Button = QtWidgets.QPushButton(self.AugmentedReality_GroupBox)
        self.ShowWordVertically_Button.setGeometry(QtCore.QRect(40, 270, 171, 41))
        self.ShowWordVertically_Button.setObjectName("ShowWordVertically_Button")
        self.Word_TextEdit = QtWidgets.QTextEdit(self.AugmentedReality_GroupBox)
        self.Word_TextEdit.setGeometry(QtCore.QRect(40, 120, 171, 41))
        self.Word_TextEdit.setObjectName("Word_TextEdit")
        self.StereoDisparityMap_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.StereoDisparityMap_GroupBox.setGeometry(QtCore.QRect(1140, 60, 251, 441))
        self.StereoDisparityMap_GroupBox.setObjectName("StereoDisparityMap_GroupBox")
        self.StereoDisparityMap_Button = QtWidgets.QPushButton(self.StereoDisparityMap_GroupBox)
        self.StereoDisparityMap_Button.setGeometry(QtCore.QRect(40, 180, 171, 41))
        self.StereoDisparityMap_Button.setObjectName("StereoDisparityMap_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoadData_GroupBox.setTitle(_translate("MainWindow", "Load Data"))
        self.LoadFolder_Button.setText(_translate("MainWindow", "Load Folder"))
        self.LoadImageL_Button.setText(_translate("MainWindow", "Load Image_L"))
        self.LoadImageR_Button.setText(_translate("MainWindow", "Load Image_R"))
        self.FindContour_GroupBox.setTitle(_translate("MainWindow", "1.Find Contour"))
        self.DrawContour_Button.setText(_translate("MainWindow", "1.1 Draw Contour"))
        self.CountRings_Button.setText(_translate("MainWindow", "1.2 Count Rings"))
        self.Calibration_GroupBox.setTitle(_translate("MainWindow", "2.Calibration"))
        self.FindCorners_Button.setText(_translate("MainWindow", "2.1 Find Corners"))
        self.FindIntrinsic_Button.setText(_translate("MainWindow", "2.2 Find Intrinsic"))
        self.FindExtrinsic_Button.setText(_translate("MainWindow", "2.3 Find Extrinsic"))
        self.FindDistortion_Button.setText(_translate("MainWindow", "2.4 Find Distortion"))
        self.ShowResult_Button.setText(_translate("MainWindow", "2.5 Show Result"))
        self.AugmentedReality_GroupBox.setTitle(_translate("MainWindow", "3.Augmented Reality"))
        self.ShowWordOnBoard_Button.setText(_translate("MainWindow", "3.1 Show Words on Board"))
        self.ShowWordVertically_Button.setText(_translate("MainWindow", "3.2 Show Words Vertically"))
        self.StereoDisparityMap_GroupBox.setTitle(_translate("MainWindow", "4.Stereo Disparity Map"))
        self.StereoDisparityMap_Button.setText(_translate("MainWindow", "4.1 Stereo Disparity Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
