# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 30, 381, 421))
        self.groupBox.setObjectName("groupBox")
        self.Show_Train_Image_Button = QtWidgets.QPushButton(self.groupBox)
        self.Show_Train_Image_Button.setGeometry(QtCore.QRect(60, 100, 241, 41))
        self.Show_Train_Image_Button.setObjectName("Show_Train_Image_Button")
        self.Show_Model_Structure_Button = QtWidgets.QPushButton(self.groupBox)
        self.Show_Model_Structure_Button.setGeometry(QtCore.QRect(60, 160, 241, 41))
        self.Show_Model_Structure_Button.setObjectName("Show_Model_Structure_Button")
        self.Show_Data_Augmentation_Button = QtWidgets.QPushButton(self.groupBox)
        self.Show_Data_Augmentation_Button.setGeometry(QtCore.QRect(60, 220, 241, 41))
        self.Show_Data_Augmentation_Button.setObjectName("Show_Data_Augmentation_Button")
        self.Show_Accuracy_And_Loss_Button = QtWidgets.QPushButton(self.groupBox)
        self.Show_Accuracy_And_Loss_Button.setGeometry(QtCore.QRect(60, 280, 241, 41))
        self.Show_Accuracy_And_Loss_Button.setObjectName("Show_Accuracy_And_Loss_Button")
        self.Inference_Button = QtWidgets.QPushButton(self.groupBox)
        self.Inference_Button.setGeometry(QtCore.QRect(60, 340, 241, 41))
        self.Inference_Button.setObjectName("Inference_Button")
        self.Load_Image_Button = QtWidgets.QPushButton(self.groupBox)
        self.Load_Image_Button.setGeometry(QtCore.QRect(60, 40, 241, 41))
        self.Load_Image_Button.setObjectName("Load_Image_Button")
        self.Show_Image_Label = QtWidgets.QLabel(self.centralwidget)
        self.Show_Image_Label.setGeometry(QtCore.QRect(560, 90, 400, 400))
        self.Show_Image_Label.setText("")
        self.Show_Image_Label.setObjectName("Show_Image_Label")
        self.Show_Confidence_Label = QtWidgets.QLabel(self.centralwidget)
        self.Show_Confidence_Label.setGeometry(QtCore.QRect(570, 30, 211, 21))
        self.Show_Confidence_Label.setText("")
        self.Show_Confidence_Label.setObjectName("Show_Confidence_Label")
        self.Show_Prediction_Label = QtWidgets.QLabel(self.centralwidget)
        self.Show_Prediction_Label.setGeometry(QtCore.QRect(570, 50, 211, 21))
        self.Show_Prediction_Label.setText("")
        self.Show_Prediction_Label.setObjectName("Show_Prediction_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1056, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "5.DeepLearning"))
        self.Show_Train_Image_Button.setText(_translate("MainWindow", "1.show train image"))
        self.Show_Model_Structure_Button.setText(_translate("MainWindow", "2.show model structure"))
        self.Show_Data_Augmentation_Button.setText(_translate("MainWindow", "3.show data augmentation"))
        self.Show_Accuracy_And_Loss_Button.setText(_translate("MainWindow", "4.show accuracy and loss"))
        self.Inference_Button.setText(_translate("MainWindow", "5.inference"))
        self.Load_Image_Button.setText(_translate("MainWindow", "load image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
